# Update versions with:
#   poetry run pre-commit autoupdate --freeze
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# custom linting arguments are defined in pyproject.toml

default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-merge-conflict
      - id: name-tests-test
        args:
          - --pytest-test-first
